#!/bin/sh

# 1) get source code
echo "Download AMReX form github"
git clone https://github.com/AMReX-Codes/amrex.git
cd amrex

# 2) build and install amrex
echo "Make install dir: " ${BOUQUET_AMReX_INSTALL_DIR}
mkdir -p ${BOUQUET_AMReX_INSTALL_DIR}

mkdir build
cd build

if ${BOUQUET_MPI} == "NO"; then
	cmake -DCMAKE_BUILD_TYPE=${BOUQUET_BUILD_TYPE} -DCMAKE_INSTALL_PREFIX=${BOUQUET_AMReX_INSTALL_DIR} -DCMAKE_Fortran_COMPILER=${BOUQUET_Fortran_COMPILER} -DCMAKE_CXX_COMPILER=${BOUQUET_CXX_COMPILER} -DCMAKE_CXX_STANDARD=${BOUQUET_CXX_STANDARD} -DAMReX_SPACEDIM=${BOUQUET_SPACEDIM} -DAMReX_EB="YES" -DAMReX_BUILD_TUTORIALS="YES" -DAMReX_OMP=${BOUQUET_OMP} ../
else
	cmake -DCMAKE_BUILD_TYPE=${BOUQUET_BUILD_TYPE} -DCMAKE_INSTALL_PREFIX=${BOUQUET_AMReX_INSTALL_DIR} -DCMAKE_Fortran_COMPILER=${BOUQUET_Fortran_COMPILER} -DCMAKE_CXX_COMPILER=${BOUQUET_CXX_COMPILER} -DCMAKE_CXX_STANDARD=${BOUQUET_CXX_STANDARD} -DAMReX_SPACEDIM=${BOUQUET_SPACEDIM} -DAMREX_EB="YES" -DAMReX_BUILD_TUTORIALS="YES" -DAMReX_OMP=${BOUQUET_OMP} -DAMReX_MPI=${BOUQUET_MPI} ../
fi

cmake --build . -- -j2 -- install
cd ..
